# for local development
version: '3.7'
services:
  frontend:
    image: vue/resume
    container_name: resume
    build:
      context: ./
      dockerfile: 'Dockerfile'
    ports:
    - '4000:80'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"